export type PortionType =
  | "slices"
  | "pieces"
  | "cups"
  | "grams"
  | "tablespoons"
  | "bowls"
  | "scoops"
  | "serving";

export type FoodCategory =
  | "Breads & Bakery"
  | "Rice & Grains"
  | "Meat & Poultry"
  | "Fish & Seafood"
  | "Eggs & Dairy"
  | "Fruits"
  | "Vegetables"
  | "Legumes & Beans"
  | "Nuts & Seeds"
  | "Fast Food & Prepared"
  | "Snacks"
  | "Drinks"
  | "Sauces & Condiments"
  | "Georgian Foods";

export type FoodDbItem = {
  /** Stable id (for UI), derived from name. */
  id: string;
  name: string;
  category: FoodCategory;
  /** Base serving grams for the default portion. */
  serving_size: number;
  /** Human unit for the default portion (e.g. "1 slice", "1 cup"). */
  serving_unit: string;
  portion_type: PortionType;
  /** Common portion quantities in the `portion_type` unit. (For grams: gram amounts.) */
  portion_options: number[];
  /**
   * Optional labels for `portion_options`.
   * Used for drinks with `portion_type: "serving"` (e.g. "1 can", "1 glass").
   */
  portion_option_labels?: Record<string, string>;
  /** Nutrition per default serving (serving_size / serving_unit). */
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
  fiber: number;
};

function makeId(name: string) {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function f(x: Omit<FoodDbItem, "id">): FoodDbItem {
  return { ...x, id: makeId(x.name) };
}

/**
 * Built-in food database.
 *
 * Values are from common USDA-style references; exact brands/recipes vary.
 * These defaults are intended for quick logging and portion scaling.
 */
export const FOOD_DATABASE: FoodDbItem[] = [
  // BREADS & BAKERY
  f({
    name: "White bread",
    category: "Breads & Bakery",
    serving_size: 30,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 79,
    protein: 2.6,
    fat: 1.0,
    carbs: 15.0,
    fiber: 0.8,
  }),
  f({
    name: "Whole wheat bread",
    category: "Breads & Bakery",
    serving_size: 36,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 91,
    protein: 4.0,
    fat: 1.4,
    carbs: 17.0,
    fiber: 2.4,
  }),
  f({
    name: "Pita bread",
    category: "Breads & Bakery",
    serving_size: 60,
    serving_unit: "1 pita",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 165,
    protein: 5.5,
    fat: 1.0,
    carbs: 33.0,
    fiber: 2.2,
  }),
  f({
    name: "Tortilla wrap",
    category: "Breads & Bakery",
    serving_size: 49,
    serving_unit: "1 wrap",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 146,
    protein: 4.0,
    fat: 3.8,
    carbs: 24.0,
    fiber: 1.8,
  }),
  f({
    name: "Croissant",
    category: "Breads & Bakery",
    serving_size: 67,
    serving_unit: "1 croissant",
    portion_type: "pieces",
    portion_options: [1, 2],
    calories: 272,
    protein: 5.0,
    fat: 14.0,
    carbs: 31.0,
    fiber: 1.7,
  }),
  f({
    name: "Bagel",
    category: "Breads & Bakery",
    serving_size: 105,
    serving_unit: "1 bagel",
    portion_type: "pieces",
    portion_options: [1, 1.5, 2],
    calories: 270,
    protein: 10.0,
    fat: 1.5,
    carbs: 53.0,
    fiber: 2.5,
  }),
  f({
    name: "Baguette",
    category: "Breads & Bakery",
    serving_size: 30,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 78,
    protein: 2.7,
    fat: 0.3,
    carbs: 15.2,
    fiber: 0.9,
  }),

  // RICE & GRAINS
  f({
    name: "White rice cooked",
    category: "Rice & Grains",
    serving_size: 186,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 242,
    protein: 4.4,
    fat: 0.4,
    carbs: 53.4,
    fiber: 0.6,
  }),
  f({
    name: "Brown rice cooked",
    category: "Rice & Grains",
    serving_size: 195,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 216,
    protein: 5.0,
    fat: 1.8,
    carbs: 44.8,
    fiber: 3.5,
  }),
  f({
    name: "Quinoa cooked",
    category: "Rice & Grains",
    serving_size: 185,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 222,
    protein: 8.1,
    fat: 3.6,
    carbs: 39.4,
    fiber: 5.2,
  }),
  f({
    name: "Oatmeal cooked",
    category: "Rice & Grains",
    serving_size: 234,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 158,
    protein: 6.0,
    fat: 3.2,
    carbs: 27.0,
    fiber: 4.0,
  }),
  f({
    name: "Pasta cooked",
    category: "Rice & Grains",
    serving_size: 140,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 220,
    protein: 8.0,
    fat: 1.3,
    carbs: 43.0,
    fiber: 2.5,
  }),
  f({
    name: "Buckwheat cooked",
    category: "Rice & Grains",
    serving_size: 168,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 155,
    protein: 5.7,
    fat: 1.0,
    carbs: 33.5,
    fiber: 4.5,
  }),
  f({
    name: "Couscous cooked",
    category: "Rice & Grains",
    serving_size: 157,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 176,
    protein: 6.0,
    fat: 0.3,
    carbs: 36.5,
    fiber: 2.2,
  }),

  // MEAT & POULTRY
  f({
    name: "Chicken breast grilled",
    category: "Meat & Poultry",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [50, 100, 150, 200, 250],
    calories: 165,
    protein: 31.0,
    fat: 3.6,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Chicken thigh",
    category: "Meat & Poultry",
    serving_size: 116,
    serving_unit: "1 thigh",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 229,
    protein: 24.0,
    fat: 14.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Chicken wing",
    category: "Meat & Poultry",
    serving_size: 34,
    serving_unit: "1 wing",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 72,
    protein: 6.4,
    fat: 5.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Ground beef 80/20",
    category: "Meat & Poultry",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [50, 100, 150, 200, 250],
    calories: 254,
    protein: 17.2,
    fat: 20.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Ground beef 90/10",
    category: "Meat & Poultry",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [50, 100, 150, 200, 250],
    calories: 176,
    protein: 20.0,
    fat: 10.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Steak sirloin",
    category: "Meat & Poultry",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [100, 150, 200, 250, 300],
    calories: 206,
    protein: 27.0,
    fat: 11.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Pork chop",
    category: "Meat & Poultry",
    serving_size: 113,
    serving_unit: "1 chop",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 231,
    protein: 25.0,
    fat: 14.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Turkey breast",
    category: "Meat & Poultry",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [50, 100, 150, 200, 250],
    calories: 135,
    protein: 29.0,
    fat: 1.6,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Lamb chop",
    category: "Meat & Poultry",
    serving_size: 100,
    serving_unit: "1 chop",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 282,
    protein: 25.0,
    fat: 20.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Bacon",
    category: "Meat & Poultry",
    serving_size: 8,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 43,
    protein: 3.0,
    fat: 3.3,
    carbs: 0.1,
    fiber: 0,
  }),
  f({
    name: "Sausage",
    category: "Meat & Poultry",
    serving_size: 68,
    serving_unit: "1 link",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 196,
    protein: 9.0,
    fat: 16.0,
    carbs: 2.0,
    fiber: 0,
  }),

  // FISH & SEAFOOD
  f({
    name: "Salmon fillet",
    category: "Fish & Seafood",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [100, 150, 200, 250, 300],
    calories: 208,
    protein: 20.0,
    fat: 13.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Tuna canned in water",
    category: "Fish & Seafood",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [50, 100, 150, 200],
    calories: 116,
    protein: 26.0,
    fat: 1.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Shrimp",
    category: "Fish & Seafood",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [50, 100, 150, 200],
    calories: 99,
    protein: 24.0,
    fat: 0.3,
    carbs: 0.2,
    fiber: 0,
  }),
  f({
    name: "Cod fillet",
    category: "Fish & Seafood",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [100, 150, 200, 250],
    calories: 82,
    protein: 18.0,
    fat: 0.7,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Tilapia",
    category: "Fish & Seafood",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [100, 150, 200, 250],
    calories: 96,
    protein: 20.0,
    fat: 1.7,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Sardines canned",
    category: "Fish & Seafood",
    serving_size: 24,
    serving_unit: "1 sardine",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 50,
    protein: 5.4,
    fat: 2.8,
    carbs: 0,
    fiber: 0,
  }),

  // EGGS & DAIRY
  f({
    name: "Egg large",
    category: "Eggs & Dairy",
    serving_size: 50,
    serving_unit: "1 egg",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 72,
    protein: 6.3,
    fat: 4.8,
    carbs: 0.4,
    fiber: 0,
  }),
  f({
    name: "Egg white",
    category: "Eggs & Dairy",
    serving_size: 33,
    serving_unit: "1 white",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 17,
    protein: 3.6,
    fat: 0.1,
    carbs: 0.2,
    fiber: 0,
  }),
  f({
    name: "Greek yogurt plain",
    category: "Eggs & Dairy",
    serving_size: 245,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 130,
    protein: 23.0,
    fat: 0.7,
    carbs: 9.0,
    fiber: 0,
  }),
  f({
    name: "Greek yogurt with fruit",
    category: "Eggs & Dairy",
    serving_size: 245,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 190,
    protein: 20.0,
    fat: 2.5,
    carbs: 24.0,
    fiber: 1.5,
  }),
  f({
    name: "Milk whole",
    category: "Eggs & Dairy",
    serving_size: 244,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 149,
    protein: 7.7,
    fat: 7.9,
    carbs: 11.7,
    fiber: 0,
  }),
  f({
    name: "Milk 2%",
    category: "Eggs & Dairy",
    serving_size: 244,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 122,
    protein: 8.1,
    fat: 4.8,
    carbs: 12.3,
    fiber: 0,
  }),
  f({
    name: "Milk skim",
    category: "Eggs & Dairy",
    serving_size: 244,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 83,
    protein: 8.3,
    fat: 0.2,
    carbs: 12.2,
    fiber: 0,
  }),
  f({
    name: "Cottage cheese",
    category: "Eggs & Dairy",
    serving_size: 226,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 206,
    protein: 28.0,
    fat: 9.0,
    carbs: 8.0,
    fiber: 0,
  }),
  f({
    name: "Cheddar cheese",
    category: "Eggs & Dairy",
    serving_size: 28,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 113,
    protein: 7.0,
    fat: 9.3,
    carbs: 0.4,
    fiber: 0,
  }),
  f({
    name: "Mozzarella",
    category: "Eggs & Dairy",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [50, 100, 150, 200, 250],
    calories: 280,
    protein: 28.0,
    fat: 17.0,
    carbs: 3.0,
    fiber: 0,
  }),
  f({
    name: "Feta cheese",
    category: "Eggs & Dairy",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [30, 50, 75, 100, 150],
    calories: 264,
    protein: 14.0,
    fat: 21.0,
    carbs: 4.0,
    fiber: 0,
  }),
  f({
    name: "Butter",
    category: "Eggs & Dairy",
    serving_size: 14,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 102,
    protein: 0.1,
    fat: 11.5,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Cream cheese",
    category: "Eggs & Dairy",
    serving_size: 14,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 51,
    protein: 0.9,
    fat: 5.1,
    carbs: 1.0,
    fiber: 0,
  }),

  // FRUITS
  f({
    name: "Banana",
    category: "Fruits",
    serving_size: 118,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 105,
    protein: 1.3,
    fat: 0.4,
    carbs: 27.0,
    fiber: 3.1,
  }),
  f({
    name: "Apple",
    category: "Fruits",
    serving_size: 182,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 95,
    protein: 0.5,
    fat: 0.3,
    carbs: 25.0,
    fiber: 4.4,
  }),
  f({
    name: "Orange",
    category: "Fruits",
    serving_size: 131,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 62,
    protein: 1.2,
    fat: 0.2,
    carbs: 15.4,
    fiber: 3.1,
  }),
  f({
    name: "Strawberries",
    category: "Fruits",
    serving_size: 152,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 49,
    protein: 1.0,
    fat: 0.5,
    carbs: 11.7,
    fiber: 3.0,
  }),
  f({
    name: "Blueberries",
    category: "Fruits",
    serving_size: 148,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 84,
    protein: 1.1,
    fat: 0.5,
    carbs: 21.4,
    fiber: 3.6,
  }),
  f({
    name: "Grapes",
    category: "Fruits",
    serving_size: 151,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 104,
    protein: 1.1,
    fat: 0.2,
    carbs: 27.3,
    fiber: 1.4,
  }),
  f({
    name: "Watermelon",
    category: "Fruits",
    serving_size: 152,
    serving_unit: "1 cup diced",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 46,
    protein: 0.9,
    fat: 0.2,
    carbs: 11.5,
    fiber: 0.6,
  }),
  f({
    name: "Mango",
    category: "Fruits",
    serving_size: 207,
    serving_unit: "1 mango",
    portion_type: "pieces",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 135,
    protein: 1.4,
    fat: 0.6,
    carbs: 35.0,
    fiber: 3.7,
  }),
  f({
    name: "Avocado",
    category: "Fruits",
    serving_size: 201,
    serving_unit: "1 avocado",
    portion_type: "pieces",
    portion_options: [0.25, 0.5, 1, 1.5],
    calories: 322,
    protein: 4.0,
    fat: 29.5,
    carbs: 17.0,
    fiber: 13.5,
  }),
  f({
    name: "Pineapple",
    category: "Fruits",
    serving_size: 165,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 82,
    protein: 0.9,
    fat: 0.2,
    carbs: 21.6,
    fiber: 2.3,
  }),
  f({
    name: "Peach",
    category: "Fruits",
    serving_size: 150,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 58,
    protein: 1.4,
    fat: 0.4,
    carbs: 14.0,
    fiber: 2.3,
  }),
  f({
    name: "Pomegranate",
    category: "Fruits",
    serving_size: 282,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [0.5, 1, 1.5],
    calories: 234,
    protein: 4.7,
    fat: 3.3,
    carbs: 52.7,
    fiber: 11.3,
  }),
  f({
    name: "Kiwi",
    category: "Fruits",
    serving_size: 69,
    serving_unit: "1 kiwi",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 42,
    protein: 0.8,
    fat: 0.4,
    carbs: 10.1,
    fiber: 2.1,
  }),

  // VEGETABLES
  f({
    name: "Broccoli",
    category: "Vegetables",
    serving_size: 91,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 31,
    protein: 2.5,
    fat: 0.3,
    carbs: 6.0,
    fiber: 2.4,
  }),
  f({
    name: "Spinach raw",
    category: "Vegetables",
    serving_size: 30,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [1, 2, 3, 4],
    calories: 7,
    protein: 0.9,
    fat: 0.1,
    carbs: 1.1,
    fiber: 0.7,
  }),
  f({
    name: "Tomato",
    category: "Vegetables",
    serving_size: 123,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 22,
    protein: 1.1,
    fat: 0.2,
    carbs: 4.8,
    fiber: 1.5,
  }),
  f({
    name: "Cucumber",
    category: "Vegetables",
    serving_size: 201,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 30,
    protein: 1.3,
    fat: 0.2,
    carbs: 7.3,
    fiber: 1.0,
  }),
  f({
    name: "Carrot",
    category: "Vegetables",
    serving_size: 61,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 25,
    protein: 0.6,
    fat: 0.1,
    carbs: 5.8,
    fiber: 1.7,
  }),
  f({
    name: "Bell pepper",
    category: "Vegetables",
    serving_size: 119,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 31,
    protein: 1.0,
    fat: 0.3,
    carbs: 7.2,
    fiber: 2.5,
  }),
  f({
    name: "Sweet potato",
    category: "Vegetables",
    serving_size: 114,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 103,
    protein: 2.3,
    fat: 0.2,
    carbs: 23.6,
    fiber: 3.8,
  }),
  f({
    name: "Regular potato",
    category: "Vegetables",
    serving_size: 150,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 130,
    protein: 3.0,
    fat: 0.2,
    carbs: 30.0,
    fiber: 2.8,
  }),
  f({
    name: "Onion",
    category: "Vegetables",
    serving_size: 110,
    serving_unit: "1 medium",
    portion_type: "pieces",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 44,
    protein: 1.2,
    fat: 0.1,
    carbs: 10.3,
    fiber: 1.9,
  }),
  f({
    name: "Corn on cob",
    category: "Vegetables",
    serving_size: 90,
    serving_unit: "1 ear",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 77,
    protein: 2.8,
    fat: 1.1,
    carbs: 17.0,
    fiber: 2.4,
  }),
  f({
    name: "Green beans",
    category: "Vegetables",
    serving_size: 125,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 34,
    protein: 1.8,
    fat: 0.2,
    carbs: 7.8,
    fiber: 4.0,
  }),
  f({
    name: "Mushrooms",
    category: "Vegetables",
    serving_size: 70,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 15,
    protein: 2.2,
    fat: 0.2,
    carbs: 2.3,
    fiber: 0.7,
  }),
  f({
    name: "Cauliflower",
    category: "Vegetables",
    serving_size: 107,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 27,
    protein: 2.1,
    fat: 0.3,
    carbs: 5.3,
    fiber: 2.1,
  }),
  f({
    name: "Eggplant",
    category: "Vegetables",
    serving_size: 82,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 20,
    protein: 0.8,
    fat: 0.1,
    carbs: 4.8,
    fiber: 2.5,
  }),

  // LEGUMES & BEANS
  f({
    name: "Chickpeas cooked",
    category: "Legumes & Beans",
    serving_size: 164,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 269,
    protein: 14.5,
    fat: 4.2,
    carbs: 45.0,
    fiber: 12.5,
  }),
  f({
    name: "Black beans cooked",
    category: "Legumes & Beans",
    serving_size: 172,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 227,
    protein: 15.2,
    fat: 0.9,
    carbs: 40.8,
    fiber: 15.0,
  }),
  f({
    name: "Lentils cooked",
    category: "Legumes & Beans",
    serving_size: 198,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 230,
    protein: 18.0,
    fat: 0.8,
    carbs: 39.9,
    fiber: 15.6,
  }),
  f({
    name: "Kidney beans cooked",
    category: "Legumes & Beans",
    serving_size: 177,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 225,
    protein: 15.3,
    fat: 0.9,
    carbs: 40.4,
    fiber: 13.1,
  }),
  f({
    name: "Hummus",
    category: "Legumes & Beans",
    serving_size: 15,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [1, 2, 3, 4],
    calories: 25,
    protein: 1.2,
    fat: 1.4,
    carbs: 2.1,
    fiber: 0.6,
  }),

  // NUTS & SEEDS
  f({
    name: "Almonds",
    category: "Nuts & Seeds",
    serving_size: 28,
    serving_unit: "28 g",
    portion_type: "grams",
    portion_options: [14, 28, 42, 56, 70],
    calories: 164,
    protein: 6.0,
    fat: 14.2,
    carbs: 6.1,
    fiber: 3.5,
  }),
  f({
    name: "Walnuts",
    category: "Nuts & Seeds",
    serving_size: 28,
    serving_unit: "28 g",
    portion_type: "grams",
    portion_options: [14, 28, 42, 56, 70],
    calories: 185,
    protein: 4.3,
    fat: 18.5,
    carbs: 3.9,
    fiber: 1.9,
  }),
  f({
    name: "Peanuts",
    category: "Nuts & Seeds",
    serving_size: 28,
    serving_unit: "28 g",
    portion_type: "grams",
    portion_options: [14, 28, 42, 56, 70],
    calories: 161,
    protein: 7.3,
    fat: 14.0,
    carbs: 4.6,
    fiber: 2.4,
  }),
  f({
    name: "Peanut butter",
    category: "Nuts & Seeds",
    serving_size: 16,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 94,
    protein: 3.6,
    fat: 8.0,
    carbs: 3.2,
    fiber: 1.0,
  }),
  f({
    name: "Almond butter",
    category: "Nuts & Seeds",
    serving_size: 16,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 98,
    protein: 3.4,
    fat: 9.0,
    carbs: 3.4,
    fiber: 1.6,
  }),
  f({
    name: "Cashews",
    category: "Nuts & Seeds",
    serving_size: 28,
    serving_unit: "28 g",
    portion_type: "grams",
    portion_options: [14, 28, 42, 56, 70],
    calories: 157,
    protein: 5.2,
    fat: 12.4,
    carbs: 8.6,
    fiber: 0.9,
  }),
  f({
    name: "Sunflower seeds",
    category: "Nuts & Seeds",
    serving_size: 28,
    serving_unit: "28 g",
    portion_type: "grams",
    portion_options: [14, 28, 42, 56, 70],
    calories: 165,
    protein: 5.5,
    fat: 14.1,
    carbs: 6.8,
    fiber: 2.7,
  }),
  f({
    name: "Chia seeds",
    category: "Nuts & Seeds",
    serving_size: 12,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 58,
    protein: 2.0,
    fat: 3.7,
    carbs: 5.1,
    fiber: 4.1,
  }),
  f({
    name: "Flaxseeds",
    category: "Nuts & Seeds",
    serving_size: 10,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 55,
    protein: 1.9,
    fat: 4.3,
    carbs: 3.0,
    fiber: 2.8,
  }),

  // FAST FOOD & PREPARED
  f({
    name: "Pizza cheese",
    category: "Fast Food & Prepared",
    serving_size: 107,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 272,
    protein: 12.0,
    fat: 10.0,
    carbs: 34.0,
    fiber: 2.5,
  }),
  f({
    name: "Pizza pepperoni",
    category: "Fast Food & Prepared",
    serving_size: 113,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 313,
    protein: 13.0,
    fat: 13.0,
    carbs: 35.0,
    fiber: 2.0,
  }),
  f({
    name: "Khachapuri",
    category: "Fast Food & Prepared",
    serving_size: 150,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 380,
    protein: 15.0,
    fat: 18.0,
    carbs: 40.0,
    fiber: 1.5,
  }),
  f({
    name: "Burger single patty",
    category: "Fast Food & Prepared",
    serving_size: 215,
    serving_unit: "1 burger",
    portion_type: "pieces",
    portion_options: [1, 2],
    calories: 540,
    protein: 28.0,
    fat: 30.0,
    carbs: 40.0,
    fiber: 3.0,
  }),
  f({
    name: "Burger double patty",
    category: "Fast Food & Prepared",
    serving_size: 300,
    serving_unit: "1 burger",
    portion_type: "pieces",
    portion_options: [1, 2],
    calories: 740,
    protein: 40.0,
    fat: 44.0,
    carbs: 45.0,
    fiber: 3.0,
  }),
  f({
    name: "French fries medium",
    category: "Fast Food & Prepared",
    serving_size: 100,
    serving_unit: "100 g",
    portion_type: "grams",
    portion_options: [75, 100, 150, 200, 250],
    calories: 312,
    protein: 3.4,
    fat: 15.0,
    carbs: 41.0,
    fiber: 3.8,
  }),
  f({
    name: "Hot dog",
    category: "Fast Food & Prepared",
    serving_size: 98,
    serving_unit: "1 hot dog",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 290,
    protein: 10.0,
    fat: 20.0,
    carbs: 18.0,
    fiber: 1.0,
  }),
  f({
    name: "Burrito",
    category: "Fast Food & Prepared",
    serving_size: 300,
    serving_unit: "1 burrito",
    portion_type: "pieces",
    portion_options: [1, 2],
    calories: 450,
    protein: 18.0,
    fat: 16.0,
    carbs: 58.0,
    fiber: 7.0,
  }),
  f({
    name: "Taco",
    category: "Fast Food & Prepared",
    serving_size: 135,
    serving_unit: "1 taco",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 210,
    protein: 9.0,
    fat: 10.0,
    carbs: 21.0,
    fiber: 3.0,
  }),
  f({
    name: "Shawarma/Doner",
    category: "Fast Food & Prepared",
    serving_size: 350,
    serving_unit: "1 wrap",
    portion_type: "pieces",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 550,
    protein: 28.0,
    fat: 28.0,
    carbs: 50.0,
    fiber: 4.0,
  }),
  f({
    name: "Sushi roll",
    category: "Fast Food & Prepared",
    serving_size: 28,
    serving_unit: "1 piece",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 37,
    protein: 1.5,
    fat: 0.3,
    carbs: 7.0,
    fiber: 0.2,
  }),
  f({
    name: "Fried chicken piece",
    category: "Fast Food & Prepared",
    serving_size: 130,
    serving_unit: "1 piece",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 320,
    protein: 20.0,
    fat: 20.0,
    carbs: 14.0,
    fiber: 0.5,
  }),
  f({
    name: "Chicken nuggets",
    category: "Fast Food & Prepared",
    serving_size: 18,
    serving_unit: "1 nugget",
    portion_type: "pieces",
    portion_options: [3, 5, 8, 10],
    calories: 48,
    protein: 2.7,
    fat: 3.0,
    carbs: 2.6,
    fiber: 0.1,
  }),
  f({
    name: "Kebab",
    category: "Fast Food & Prepared",
    serving_size: 100,
    serving_unit: "1 skewer",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 176,
    protein: 26.0,
    fat: 7.0,
    carbs: 0,
    fiber: 0,
  }),

  // SNACKS
  f({
    name: "Protein bar",
    category: "Snacks",
    serving_size: 60,
    serving_unit: "1 bar",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 210,
    protein: 20.0,
    fat: 7.0,
    carbs: 23.0,
    fiber: 6.0,
  }),
  f({
    name: "Granola bar",
    category: "Snacks",
    serving_size: 42,
    serving_unit: "1 bar",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 190,
    protein: 3.0,
    fat: 7.0,
    carbs: 30.0,
    fiber: 2.0,
  }),
  f({
    name: "Chips/crisps",
    category: "Snacks",
    serving_size: 28,
    serving_unit: "28 g",
    portion_type: "grams",
    portion_options: [14, 28, 42, 56, 70],
    calories: 152,
    protein: 2.0,
    fat: 10.0,
    carbs: 15.0,
    fiber: 1.0,
  }),
  f({
    name: "Popcorn",
    category: "Snacks",
    serving_size: 8,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [1, 2, 3, 4],
    calories: 31,
    protein: 1.0,
    fat: 0.4,
    carbs: 6.2,
    fiber: 1.2,
  }),
  f({
    name: "Dark chocolate",
    category: "Snacks",
    serving_size: 10,
    serving_unit: "1 square",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 55,
    protein: 0.7,
    fat: 3.8,
    carbs: 5.3,
    fiber: 1.2,
  }),
  f({
    name: "Milk chocolate",
    category: "Snacks",
    serving_size: 10,
    serving_unit: "1 square",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 53,
    protein: 0.8,
    fat: 3.2,
    carbs: 5.7,
    fiber: 0.5,
  }),
  f({
    name: "Crackers",
    category: "Snacks",
    serving_size: 30,
    serving_unit: "5 crackers",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 130,
    protein: 2.0,
    fat: 4.5,
    carbs: 20.0,
    fiber: 1.0,
  }),
  f({
    name: "Trail mix",
    category: "Snacks",
    serving_size: 28,
    serving_unit: "28 g",
    portion_type: "grams",
    portion_options: [14, 28, 42, 56, 70],
    calories: 137,
    protein: 3.5,
    fat: 9.0,
    carbs: 13.0,
    fiber: 2.0,
  }),
  f({
    name: "Rice cakes",
    category: "Snacks",
    serving_size: 9,
    serving_unit: "1 cake",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 35,
    protein: 0.7,
    fat: 0.3,
    carbs: 7.3,
    fiber: 0.3,
  }),

  // DRINKS
  f({
    name: "Orange juice",
    category: "Drinks",
    serving_size: 250,
    serving_unit: "1 glass (250 ml)",
    portion_type: "serving",
    portion_options: [200, 240, 250, 350],
    portion_option_labels: {
      "200": "Small glass",
      "240": "1 cup",
      "250": "1 glass",
      "350": "Large glass",
    },
    calories: 112,
    protein: 1.7,
    fat: 0.5,
    carbs: 25.8,
    fiber: 0.5,
  }),
  f({
    name: "Apple juice",
    category: "Drinks",
    serving_size: 250,
    serving_unit: "1 glass (250 ml)",
    portion_type: "serving",
    portion_options: [200, 240, 250, 350],
    portion_option_labels: {
      "200": "Small glass",
      "240": "1 cup",
      "250": "1 glass",
      "350": "Large glass",
    },
    calories: 114,
    protein: 0.2,
    fat: 0.3,
    carbs: 28.0,
    fiber: 0.2,
  }),
  f({
    name: "Coca-Cola",
    category: "Drinks",
    serving_size: 330,
    serving_unit: "1 can (330 ml)",
    portion_type: "serving",
    portion_options: [240, 250, 330, 500, 480, 1000, 2000],
    portion_option_labels: {
      "250": "1 glass",
      "330": "1 can",
      "240": "1 cup",
      "500": "Small bottle",
      "480": "Large bottle poured (2 cups)",
      "1000": "1 liter bottle",
      "2000": "2 liter bottle",
    },
    calories: 140,
    protein: 0,
    fat: 0,
    carbs: 39.0,
    fiber: 0,
  }),
  f({
    name: "Coffee black",
    category: "Drinks",
    serving_size: 240,
    serving_unit: "Small cup (240 ml)",
    portion_type: "serving",
    portion_options: [30, 240, 350, 470],
    portion_option_labels: {
      "30": "Espresso shot",
      "240": "Small cup",
      "350": "Medium cup",
      "470": "Large cup",
    },
    calories: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Coffee with milk",
    category: "Drinks",
    serving_size: 240,
    serving_unit: "Small cup (240 ml)",
    portion_type: "serving",
    portion_options: [30, 240, 350, 470],
    portion_option_labels: {
      "30": "Espresso shot",
      "240": "Small cup",
      "350": "Medium cup",
      "470": "Large cup",
    },
    calories: 30,
    protein: 1.5,
    fat: 1.0,
    carbs: 3.0,
    fiber: 0,
  }),
  f({
    name: "Latte",
    category: "Drinks",
    serving_size: 350,
    serving_unit: "Medium cup (350 ml)",
    portion_type: "serving",
    portion_options: [30, 240, 350, 470],
    portion_option_labels: {
      "30": "Espresso shot",
      "240": "Small cup",
      "350": "Medium cup",
      "470": "Large cup",
    },
    calories: 190,
    protein: 10.0,
    fat: 7.0,
    carbs: 20.0,
    fiber: 0,
  }),
  f({
    name: "Cappuccino",
    category: "Drinks",
    serving_size: 240,
    serving_unit: "Small cup (240 ml)",
    portion_type: "serving",
    portion_options: [30, 240, 350, 470],
    portion_option_labels: {
      "30": "Espresso shot",
      "240": "Small cup",
      "350": "Medium cup",
      "470": "Large cup",
    },
    calories: 120,
    protein: 6.0,
    fat: 4.0,
    carbs: 12.0,
    fiber: 0,
  }),
  f({
    name: "Smoothie fruit",
    category: "Drinks",
    serving_size: 300,
    serving_unit: "1 cup (300 ml)",
    portion_type: "serving",
    portion_options: [200, 240, 300, 350],
    portion_option_labels: {
      "200": "Small glass",
      "240": "1 cup",
      "300": "1 cup (300 ml)",
      "350": "Large glass",
    },
    calories: 180,
    protein: 3.0,
    fat: 2.0,
    carbs: 40.0,
    fiber: 4.0,
  }),
  f({
    name: "Protein shake",
    category: "Drinks",
    serving_size: 30,
    serving_unit: "1 scoop",
    portion_type: "scoops",
    portion_options: [1, 1.5, 2],
    calories: 120,
    protein: 24.0,
    fat: 2.0,
    carbs: 3.0,
    fiber: 1.0,
  }),
  f({
    name: "Beer",
    category: "Drinks",
    serving_size: 330,
    serving_unit: "1 can (330 ml)",
    portion_type: "serving",
    portion_options: [330, 500],
    portion_option_labels: {
      "330": "Glass/can",
      "500": "Pint/bottle",
    },
    calories: 153,
    protein: 1.6,
    fat: 0,
    carbs: 13.0,
    fiber: 0,
  }),
  f({
    name: "Wine red",
    category: "Drinks",
    serving_size: 148,
    serving_unit: "1 glass (148 ml)",
    portion_type: "serving",
    portion_options: [125, 148, 250],
    portion_option_labels: {
      "125": "Small glass",
      "148": "Standard glass",
      "250": "Large glass",
    },
    calories: 125,
    protein: 0.1,
    fat: 0,
    carbs: 3.9,
    fiber: 0,
  }),

  // SAUCES & CONDIMENTS
  f({
    name: "Ketchup",
    category: "Sauces & Condiments",
    serving_size: 17,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 20,
    protein: 0.2,
    fat: 0.0,
    carbs: 5.0,
    fiber: 0.1,
  }),
  f({
    name: "Mayonnaise",
    category: "Sauces & Condiments",
    serving_size: 15,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 94,
    protein: 0.1,
    fat: 10.0,
    carbs: 0.1,
    fiber: 0,
  }),
  f({
    name: "Mustard",
    category: "Sauces & Condiments",
    serving_size: 5,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [1, 2, 3, 4],
    calories: 3,
    protein: 0.2,
    fat: 0.2,
    carbs: 0.3,
    fiber: 0.2,
  }),
  f({
    name: "Soy sauce",
    category: "Sauces & Condiments",
    serving_size: 16,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 9,
    protein: 1.3,
    fat: 0,
    carbs: 0.8,
    fiber: 0.1,
  }),
  f({
    name: "Olive oil",
    category: "Sauces & Condiments",
    serving_size: 14,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 119,
    protein: 0,
    fat: 13.5,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Honey",
    category: "Sauces & Condiments",
    serving_size: 21,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 64,
    protein: 0.1,
    fat: 0,
    carbs: 17.3,
    fiber: 0,
  }),
  f({
    name: "Maple syrup",
    category: "Sauces & Condiments",
    serving_size: 20,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 52,
    protein: 0,
    fat: 0,
    carbs: 13.4,
    fiber: 0,
  }),
  f({
    name: "Hot sauce",
    category: "Sauces & Condiments",
    serving_size: 5,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [1, 2, 3, 4],
    calories: 5,
    protein: 0,
    fat: 0,
    carbs: 1.0,
    fiber: 0.2,
  }),
  f({
    name: "Ranch dressing",
    category: "Sauces & Condiments",
    serving_size: 15,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 73,
    protein: 0.2,
    fat: 7.6,
    carbs: 1.2,
    fiber: 0,
  }),
  f({
    name: "Balsamic vinegar",
    category: "Sauces & Condiments",
    serving_size: 16,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [0.5, 1, 2, 3],
    calories: 14,
    protein: 0,
    fat: 0,
    carbs: 2.7,
    fiber: 0,
  }),

  // GEORGIAN FOODS
  f({
    name: "Khachapuri Adjarian",
    category: "Georgian Foods",
    serving_size: 400,
    serving_unit: "1 boat",
    portion_type: "pieces",
    portion_options: [0.5, 1, 1.5],
    calories: 900,
    protein: 35.0,
    fat: 55.0,
    carbs: 70.0,
    fiber: 2.0,
  }),
  f({
    name: "Khachapuri Imeruli",
    category: "Georgian Foods",
    serving_size: 150,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 380,
    protein: 15.0,
    fat: 18.0,
    carbs: 40.0,
    fiber: 1.5,
  }),
  f({
    name: "Khinkali",
    category: "Georgian Foods",
    serving_size: 70,
    serving_unit: "1 khinkali",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 120,
    protein: 6.0,
    fat: 5.0,
    carbs: 13.0,
    fiber: 0.8,
  }),
  f({
    name: "Lobiani",
    category: "Georgian Foods",
    serving_size: 150,
    serving_unit: "1 slice",
    portion_type: "slices",
    portion_options: [1, 2, 3, 4],
    calories: 350,
    protein: 12.0,
    fat: 12.0,
    carbs: 48.0,
    fiber: 6.0,
  }),
  f({
    name: "Pkhali",
    category: "Georgian Foods",
    serving_size: 30,
    serving_unit: "1 tbsp",
    portion_type: "tablespoons",
    portion_options: [1, 2, 3, 4],
    calories: 45,
    protein: 1.5,
    fat: 3.0,
    carbs: 3.0,
    fiber: 1.5,
  }),
  f({
    name: "Churchkhela",
    category: "Georgian Foods",
    serving_size: 100,
    serving_unit: "1 piece",
    portion_type: "pieces",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 380,
    protein: 6.0,
    fat: 10.0,
    carbs: 70.0,
    fiber: 3.0,
  }),
  f({
    name: "Badrijani",
    category: "Georgian Foods",
    serving_size: 80,
    serving_unit: "1 roll",
    portion_type: "pieces",
    portion_options: [1, 2, 3, 5],
    calories: 110,
    protein: 3.0,
    fat: 7.0,
    carbs: 9.0,
    fiber: 2.0,
  }),
  f({
    name: "Mtsvadi/Shashlik",
    category: "Georgian Foods",
    serving_size: 150,
    serving_unit: "1 skewer",
    portion_type: "pieces",
    portion_options: [1, 2, 3],
    calories: 280,
    protein: 30.0,
    fat: 17.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Lobio",
    category: "Georgian Foods",
    serving_size: 200,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 220,
    protein: 12.0,
    fat: 5.0,
    carbs: 32.0,
    fiber: 10.0,
  }),
  f({
    name: "Chicken Tabaka",
    category: "Georgian Foods",
    serving_size: 300,
    serving_unit: "half chicken",
    portion_type: "pieces",
    portion_options: [0.5, 1, 1.5],
    calories: 520,
    protein: 45.0,
    fat: 35.0,
    carbs: 0,
    fiber: 0,
  }),
  f({
    name: "Elarji",
    category: "Georgian Foods",
    serving_size: 250,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 350,
    protein: 12.0,
    fat: 15.0,
    carbs: 42.0,
    fiber: 1.0,
  }),
  f({
    name: "Ghomi",
    category: "Georgian Foods",
    serving_size: 200,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 180,
    protein: 4.0,
    fat: 1.0,
    carbs: 40.0,
    fiber: 1.5,
  }),
  f({
    name: "Satsivi",
    category: "Georgian Foods",
    serving_size: 200,
    serving_unit: "1 cup",
    portion_type: "cups",
    portion_options: [0.5, 1, 1.5, 2],
    calories: 310,
    protein: 16.0,
    fat: 22.0,
    carbs: 10.0,
    fiber: 2.0,
  }),
];

export const FOOD_CATEGORIES: { key: string; label: string; category?: FoodCategory }[] = [
  { key: "all", label: "All" },
  { key: "favorites", label: "Favorites" },
  { key: "recent", label: "Recent" },
  { key: "breads", label: "Breads", category: "Breads & Bakery" },
  { key: "grains", label: "Grains", category: "Rice & Grains" },
  { key: "meat", label: "Meat", category: "Meat & Poultry" },
  { key: "fish", label: "Fish", category: "Fish & Seafood" },
  { key: "dairy", label: "Dairy", category: "Eggs & Dairy" },
  { key: "fruits", label: "Fruits", category: "Fruits" },
  { key: "veg", label: "Vegetables", category: "Vegetables" },
  { key: "beans", label: "Beans", category: "Legumes & Beans" },
  { key: "nuts", label: "Nuts", category: "Nuts & Seeds" },
  { key: "fast", label: "Fast food", category: "Fast Food & Prepared" },
  { key: "snacks", label: "Snacks", category: "Snacks" },
  { key: "drinks", label: "Drinks", category: "Drinks" },
  { key: "sauces", label: "Sauces", category: "Sauces & Condiments" },
  { key: "georgian", label: "Georgian", category: "Georgian Foods" },
];

